from LinkedList import LinkedList
from SearchTree import BinarySearchTree

list1 = LinkedList(1)
list2 = LinkedList()
list1.addNode(2)
list1.addNode(3)
list1.addNode(4)
list1.addNode(5)
list1.addNode(6)
list1.addNode(7)
#list1.printList()
#print(list1.getLength())
#list2 = LinkedList()
#list1.reverseList()
#list1.printList()
#list1.deleteTail()
list1.deleteValue(8)
list2.deleteValue(10)
list1.printList()
searchList = BinarySearchTree()
searchList.addNode(5)
searchList.addNode(4)
searchList.addNode(6)
searchList.addNode(3)
searchList.addNode(7)
#print(searchList.findValue(2))
print(searchList.treeHeight(searchList.head))